<a href="https://colab.research.google.com/github/19neloyk/article-based-AI-investment/blob/master/SeniorProjectAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
def frequencyFinder(article):
    article = str(article)
    word = ''
    arrayOfWords = []
    disWorFrequencies = []

    for element in article:
        if element in ('.',' ',',','(',')'):
            if len(arrayOfWords) == 0:
                arrayOfWords.append(word)
                disWorFrequencies.append(1)
                word = ''
            for index in range(0,len(arrayOfWords)):
                if word == arrayOfWords[index]:
                    disWorFrequencies[index] += 1
                    word = ''
                    break;
                elif index == len(arrayOfWords)-1:
                    arrayOfWords.append(word)
                    disWorFrequencies.append(1)
                    word = ''
        else:
            word += element

    index = 0

    while index < len(arrayOfWords):
        for element in ['','the', 'to', 'a', 'and', 'in', 'as']:
            if element == arrayOfWords[index]:
                del arrayOfWords[index]
                del disWorFrequencies[index]
        index = index +1

    descendingArray = []
    descendingWordFrequencies = []

    for index in range(0,len(arrayOfWords)):
        holderPosition = 0
        for position in range(0,len(arrayOfWords)):
            if disWorFrequencies[position] > disWorFrequencies[holderPosition]:
                holderPosition = position
        descendingArray.append(arrayOfWords[holderPosition])
        descendingWordFrequencies.append(disWorFrequencies[holderPosition])
        del arrayOfWords[holderPosition]
        del disWorFrequencies[holderPosition]

#     for index in range(0, len(descendingArray)):
#         spaces = 17 - len(descendingArray[index])
#         print((descendingArray[index]) + spaces*' ' + str(descendingWordFrequencies[index]))
    
    dictionaryOfWords = {}
   
    dictionaryLength = 1000 # Remember, 0 < dictionaryLength <= len(descendingArray)
                           # Takes the top dictionaryLength-ist words
    for wordIndex in range(0,dictionaryLength): 
      dictionaryOfWords[descendingArray[wordIndex]] = descendingWordFrequencies[wordIndex]
    return dictionaryOfWords

referenceDict = frequencyFinder(' Tesla to employees: if you leak  well catch you  well fire you  and we might sue you    Teslas new safety features really push you to stay in your lane    Tesla sued by family of man killed in Autopilot-related crash    The court has approved Elon Musks new agreement to let lawyers oversee his Tesla tweets    Tesla has slashed the price of its solar panels in an attempt to revive sales    Tesla lost $702 million last quarter after drop in Model 3 deliveries    Teslas new AI chip isnt a silver bullet for self-driving cars    Its Elon Musk vs. everyone else in the race for fully driverless cars    Tesla now sells electric cars with 370 miles of range    Former Tesla Model S chief engineer takes over at EV startup Lucid Motors    Teslas new self-driving chip is here  and this is your best look yet    Here are Elon Musks wildest predictions about Teslas self-driving cars    Elon Musk says Tesla will allow aggressive Autopilot mode with slight chance of a fender bender    Heres how to watch Teslas self-driving event today    Tesla gets restraining order on short-seller who photographed employees    What if Elon Musks $420 dream hadnt gone up in smoke?     Teslas original plan for the $35 000 Model 3 is dead     Teslas $35 000 Model 3 is no longer available to order online    Tesla still isnt getting enough batteries from Panasonic    Fiat Chrysler will pay Tesla to dodge billions in emissions fines    Elon Musk explains the camera inside Teslas Model 3    Elon Musk ordered to work things out with the SEC over his tweets    Tesla is selling fewer cars  but says it has sufficient cash    Your Tesla can now change lanes without asking permission    Tesla penalized for violating hazardous waste law at California factory    Tesla Model 3 hack shows new cars can snitch on owners after a wreck    Tesla changes return policy after Elon Musks contradictory tweets    Teslas $35 000 Model 3 still isnt here    Tesla is adding a stop light warning to Autopilot     Chinese EV startup XPeng is at the center of major trade secret disputes with Apple and Tesla    Elon Musk says the SECs attempt to hold him in contempt is virtually wrong at every level    Tesla brings back its customer referral program  with fewer free cars    Tesla accuses self-driving startup Zoox and former employees of trade secret theft    Tesla delays price hike because of unusually high volume of last-minute orders    The SEC says Elon Musk is in blatant violation of securities fraud settlement    Elon Musks last two weeks have been a wild ride    My brief but familiar ride in Teslas brand-new Model Y    Watch this supercut of Elon Musk unveiling Teslas new Model Y    Tesla Model Y preorders are now live    Tesla Model Y announced: release set for 2020  price starts at $47 000    Watch the Tesla Model Y reveal live    What to expect at Teslas Model Y event    The Model Y will be a test of Teslas popularity    Tesla Model Y: Elon Musks fifth electric car is a compact SUV    Tesla allegedly hacked  spied on  and followed Gigafactory whistleblower: report    Elon Musk says the SEC is making an unconstitutional power grab over his tweets    Another former Tesla security manager says the company spied on employees    Tesla will raise prices on its cars  reverses plan to close stores    Elon Musks high-speed tunnel project is the big loser in Chicagos race for mayor    German regulators tell Tesla to drop gas savings from pricing    Can a judge order Elon Musk to delete his Twitter account?    Tesla launches faster third generation Supercharger     The Polestar 2s secret weapon against the Tesla Model 3 is native Android Auto    Tesla competitors made a big splash at last years Geneva Motor Show  so where are they now?     Tesla Model Y SUV will be unveiled March 14th    Tesla makes huge price cuts to Model S and Model X     Teslas controversial full self-driving version of Autopilot is back    Tesla will close most of its stores and only sell cars online    Teslas promised $35 000 Model 3 is finally here    Tesla is making a mystery announcement at 2PM PT    The Polestar 2 is a Google-powered all-electric Tesla competitor    Elon Musk might be held in contempt of court over a Tesla tweet    Zeros new electric motorcycle justifies the comparisons to Tesla    The political winds in Chicago are blowing against Elon Musks high-speed tunnel project    Teslas Model 3 was the best-selling EV in the world last year    Elon Musk pokes fun at himself while hosting PewDiePies popular Meme Review    Consumer Reports reverses itself again  no longer recommends Tesla Model 3    Teslas latest challenge is finding new customers for the Model 3    Teslas new Dog and Sentry modes take care even when you dont    Autopilot is disabled on Teslas first Model 3 deliveries in Europe    Amazon invests in self-driving car startup run by former Google and Tesla executives    Tesla makes its first Model 3 deliveries in Europe    Teslas Model 3 pricing inches closer to $35 000 target    Tesla opens Amazon store that sells company-branded merch    Volkswagen will use Tesla battery packs in some of its US charging stations     No  Elon  the Navigate on Autopilot feature is not full self-driving     Tesla posts back-to-back profits for the first time    Tesla fined $29 365 for safety hazards in Model 3 production tent    Tesla raised prices at its Supercharger stations     Tesla cutting 7 percent of workforce  says Elon Musk    Tesla to end customer referral program  Elon Musk says    Teslas Model 3 will be the prime target at upcoming hacker contest    Daimler is beating Tesla to making semi-autonomous big rigs    The starting price of a Tesla Model S will soon be $18 000 higher    Tesla allows people in Europe and China to start configuring Model 3s    Tesla cuts vehicle prices by $2 000 to offset shrinking EV tax credit    The Verge 2018 tech report card: Tesla    Tesla adds Oracle founder Larry Ellison to board of directors     Elon Musk promises 100 percent Tesla Supercharger coverage in Europe next year    Teslas competition for the Model Y is growing quickly in China    Elon Musk is the first influencer CEO    I took a ride through Elon Musks new tunnel in California    Apple hires designer Andrew Kim away from Tesla    Porsche and BMW unveil EV charger thats three times faster than Teslas    Tesla drops prices in China after the government suspends tariffs    Elon Musk doesnt respect the SEC  which is still investigating Tesla    Elon Musk says nobody is approving his tweets after the SEC settlement    Police may have used Teslas Autopilot feature to stop driver asleep at the wheel    The Chevy Volt is dead; long live the Chevy Volt    Black Tesla factory workers describe racism and discrimination  NYT reports    Tesla will live and die by the Gigafactory    Why so many people think Elon Musk is a hero  or a villain     Elon Musk wont be smoking weed in public again  NASA admin says    What kind of company town will Tesla build around its Gigafactories?    Tesla releases track mode and a new key fob for the Model 3    Teslas new chairwoman is walking into SEC and DOJ probes    Tesla has found a new chairperson to replace Elon Musk    Teslas on-site health clinic accused of undercounting worker injuries    Teslas Navigate on Autopilot is like Waze on steroids    Tesla subpoenaed in the SECs Model 3 investigation    Tesla is what happens when you run a car company like a tech company    Elon Musk doesnt care if people buy his Blade Runner pickup truck    Teslas Navigate on Autopilot update is now live     Tesla Model 3 production reportedly under investigation by the FBI    Elon Musk successfully cosplays as a normal car company CEO    Teslas Model Y crossover is ready for production  Elon Musk says    Tesla rides Model 3s popularity to its first profit in two years    Tesla adds $1 000 to price tag of midrange Model 3 that was announced last week    Elon Musk says the Boring Companys first tunnel under LA will open December 10th    Watch a Tesla Model S get stolen with a key fob hack    Tesla stopped promoting the Full Self-Driving option for its cars    Elon Musks Teslaquila is actually a good idea    Tesla is now selling a cheaper Model 3 with a 260-mile battery starting at $45 000    Court approves Elon Musks securities fraud settlement with the SEC    Elon Musk eyes early 2019 release for Teslas custom AI chip    Tracking Elon Musks SEC battle through the plot of good TV show Billions    Tesla promises all cars ordered by October 15th will qualify for $7 500 tax break    If James Murdoch is the new Tesla chairman  thats bad news for Elon Musk    Tesla sued by Nevada for failure to pay $650 000 in taxes    Tesla adds Atari games and dash camera feature in new software update    After the SEC settlement  who will review Elon Musks tweets?    Teslas first Autopilot safety report is short on details    Teslas breakneck pace produced more than 53 000 Model 3s this quarter    Elon Musk forced to step down as chairman of Tesla  remains CEO    What Teslas union-busting trial means for the rest of Silicon Valley    Elon Musk reportedly asks Tesla employees to test full self-driving version of Autopilot      Elon Musk sued by SEC for securities fraud    Porsche says that it will no longer make diesel vehicles     SpaceX gets into space tourism while the Department of Justice gets into Tesla    Tesla Model 3 awarded five-star safety rating    Teslas long-awaited dash cam functionality will arrive in the next software update    Tesla is reportedly under criminal investigation for Elon Musks tweets    A tale of two CEOs: Tim Cook demonstrates what some want from Elon Musk    Teslas global finance head is leaving the company     Tesla is bringing back its wireless smartphone charger at a discount    Teslas keyless entry vulnerable to spoofing attack  researchers find    The Air Force is determining the appropriate process for Elon Musk smoking pot    If Tesla goes up in smoke  it wont be because Elon Musk hit a blunt    Teslas accounting and HR heads resign on the same day     The real Tesla killer might be inside the factory    Elon Musk teases electric plane design and smokes weed on Joe Rogan podcast    When Elon Musk tweets  no one can ignore it    Tesla releases a sleek but slow wireless charger for your smartphone    Tesla properly cautioned shareholders about Model 3 struggles  court rules    Tesla will remain public  Elon Musk says    This Week in Elon    Tesla challenger Lucid Motors also in talks with Saudi Arabia for reported $1 billion funding    Chinas NIO files for IPO in the US in push to compete with Tesla    Tesla eyes cost savings so it can make $25 000 cars in three years  Elon Musk tells MKBHD    Vergecast: This week in Twitter  Elon Musk  and batteries    Tesla said to seek number 2 exec as Musks behavior angers board    Tesla allegedly covered up drug trafficking and spied on employees at the Gigafactory  whistleblower says    Elon Musk says hes been talking to Saudi Arabia about taking Tesla private    Elon Musk is still seeking funding to take Tesla private  says report    Teslas chief vehicle engineer returns to Apple    For Elon Musk  the worst part of a publicly traded company was the public    Heres how Elon Musk could take Tesla private    Elon Musk says he might take Tesla private for $420 per share    Teslas autonomous coast-to-coast drive on hold while Autopilot team focuses on safety    Tesla is finally making money on the Model 3    Tesla is adding Atari games to the in-car display with next software update    Tesla whistleblower countersues over Elon Musks defamatory statements    Tesla briefly offered a $1 500 surfboard     SpaceXs hyperloop race was all about maximum speed (and celebrating Elon Musk)    Twitter will lock your account if you change your display name to Elon Musk    Nomads new wireless charger is cleverly designed to upgrade a Tesla Model 3    Elon Musk cant stop tweeting  but so far it doesnt matter    Elon Musk  DeepMind founders  and others sign pledge to not develop lethal AI weapon systems    Tesla will be the first automaker to lose the federal tax credit for electric cars    Tesla drops reservation system for Americans and Canadians looking to buy their Model 3     Tesla signs agreement to build cars in China    Elon Musks mini-submarine not practical for Thailand cave rescue  say authorities    Trade war bumps up Tesla prices in China     Elon Musk says SpaceX is building a kid-sized submarine to rescue trapped soccer team    Elon Musk promises to send SpaceX  Boring Company engineers to Thailand to help cave rescue    Tesla lost top engineer just before hitting Elon Musks Model 3 goal    Tesla reportedly hits Model 3 manufacturing goal hours after its deadline     Tesla keeps changing how it builds the Model 3    Tesla battery reignited twice after fatal crash in Florida: report    The gospel of Elon Musk  according to his flock    Tesla built a giant tent to expand production of the Model 3    Tesla closes a dozen solar installation centers as part of recent layoffs    Elon Musk wants cobalt out of his batteries  heres why thats a challenge    Tesla sues ex-employee for hacking  theft  and leaking to the press    Autopilot Buddy that tricks Tesla vehicles declared unsafe by US    Elon Musk emailed all of Tesla about attempted sabotage by an employee    Heres how Elon Musk might use rocket thrusters on the new Tesla Roadster    Elon Musk says the Chicago tunnel project could start construction in three to four months     Elon Musks Boring Company approved to build high-speed Chicago transit link    Tesla lays off thousands of workers as part of a company-wide restructuring    Tesla will start rolling out its full self-driving package in August  Elon Musk says    Teslas Autopilot steered car toward barrier before deadly crash  investigators say    Tesla is planning to offer a free trial for Autopilot    Tesla is making 3 500 Model 3 vehicles a week  Elon Musk says    Teslas annual shareholder meeting will decide Elon Musks future    Tesla can change so much with over-the-air updates that its messing with some owners heads    Consumer Reports reverses course and now recommends the Tesla Model 3    Tesla Model 3 drives 606 miles on a single charge in hypermiling record    Tesla settles with vehicle owners over delayed Autopilot updates    Elon Musk thinks you can crowdsource truth  but thats not how the internet works    Tesla Model 3 updates coming after Consumer Reports found big flaws    Tesla needs to sell more expensive Model 3s so the company doesnt die  Musk says    Grimes is changing her name to the symbol for the speed of light  encouraged by Elon Musk    The biggest news from Elon Musks Boring Company meeting in LA    Tesla crash involving Autopilot prompts federal investigation    Tesla rejected more advanced driver monitoring features on its cars    Elon Musk plans to offer free test rides through LA tunnel in a few months    This blessed Chrome extension replaces Elon Musk with Grimess Boyfriend    Tesla will regularly release data about the safety of Autopilot  Elon Musk says    Elon Musk says Tesla Model Y will be a manufacturing revolution    Tesla earned and burned a record amount of cash in most recent quarter    Tesla sued for $2 billion by hydrogen truck startup over alleged patent infringement    British Tesla driver banned after caught in the passenger seat while Autopilot was engaged    How Tesla and Waymo are tackling a major problem for self-driving cars: data    How Elon Musk could recover rockets with balloons  just not the party kind    Elon Musk says Tesla will build Model 3s 24/7 until the end of June    New rules on making cars in China could help Tesla  or give it even more to worry about    Tesla temporarily stops Model 3 production line    Tesla reportedly failed to disclose some worker injuries at itsfactory    Tesla relied on too many robots to build the Model 3  Elon Musk says    Tesla booted from investigation into fatal Autopilot crash     SpaceXs Earth views need a license now  probably thanks to the Tesla stunt    Tesla misses production goal of 2 500 Model 3s a week    Tesla is making over 2 000 Model 3s a week  as crucial deadline approaches    Tesla says Autopilot was engaged during fatal Model X crash    Tesla issues its largest recall ever voluntarily over faulty Model S steering    SF Motors is exactly the kind of EV startup Elon Musk complained to Trump about    Tesla defends Autopilot after fatal Model X crash    Elon Musk has removed Tesla and SpaceXs Facebook pages after Twitter challenge    Elon Musks new $2.6 billion compensation plan approved by Tesla shareholders    Elon Musk says his comedy project with former Onion staffers is called Thud!    Tesla files permit for restaurant and Supercharger station in Santa Monica    Tesla raises prices at its Supercharger stations    Elon Musk still thinks a Mars colony will save us from a future dark age    How to watch Elon Musks Q&A; at SXSW    Elon Musk and the creator of Westworld made an inspirational trailer for the Falcon Heavy launch    Teslas toughest competition ever was on display in Geneva    Elon Musk tweeted at the president to push China on car tariffs  and Trump read the tweets on TV    Jaguars electric SUV is cheaper than a Tesla Model X ors    Geneva Motor Show will be Europes chance to show off its Tesla killers    Tesla will supply free charging stations to office parking lots    Tesla accused of knowingly selling defective vehicles in new lawsuit    Elon Musk leaves board of AI safety group to avoid conflict of interest with Tesla    Teslas cloud was used by hackers to mine cryptocurrency    Track Elon Musks Tesla Roadster in space with this aptly named website    We drove a Tesla Model 3 around New York with MKBHD    In todays episode of Circuit Breaker Live  we take a ride in the Tesla Model 3    Elon Musk made history launching a car into space. Did he make art too?    Tesla faces a critical year  but Elon Musk is obsessed with the future    Lyft names Teslas Jon McNeill as chief operating officer    Elon Musks Tesla overshot Mars orbit  but it wont reach the asteroid belt as claimed    Elon Musk still doesnt think LIDAR is necessary for fully driverless cars    Tesla burns through $2 billion in 2017    Tesla still hasnt completed its coast-to-coast autonomous drive    Sending a Tesla into space wasnt such a dumb idea    Ride along with the dummy driving Elon Musks Tesla to Mars    Here are four things we learned from Elon Musk before the first Falcon Heavy launch    SpaceX animation shows what Elon Musks Roadster will look like on its way toward Mars    Tesla is helping South Australia build what will be the worlds largest virtual power plant    Looks like this SpaceX dummy will ride Musks Tesla Roadster into space tomorrow    Report: Tesla is partnering with companies to build on-site charging stations for its Semi truck    Elon Musk plans Boring Co. flamethrower rebranding to avoid customs scrutiny    Tesla will sell its solar power products at 800 Home Depot stores    All-Tesla racing series gets the green light    California politician will seek sale ban on Elon Musks Boring Company flamethrower      Heres Elon Musks $500 Boring Company flamethrower    Tesla Model 3 delays persist  reportedly due to Gigafactory problems    Tesla Model S plows into a fire truck while using Autopilot    Tesla stakes Elon Musks salary on plan to become bigger than Amazon    The Boring Companys plan to dig a longer tunnel under Los Angeles is up in the air    Hyundais hydrogen-powered Nexo can drive further and charge faster than a Tesla    Uber hires Teslas lead battery expert to help power its flying car service    Tesla reports best year ever for deliveries  but falls further behind on Model 3 goals    Tesla Model 3 driven from LA to New York in 50 hours    The Verge 2017 tech report card: Tesla    Elon Musk shows off the Tesla Roadster that SpaceX will send beyond Mars    NIOs China-only electric SUV will cost half as much as a Tesla Model X    Tesla is prohibiting commercial drivers from using its Supercharger stations    This electric truck startup thinks it can beat Tesla to market    PepsiCo orders 100 Tesla Semi trucks in largest preorder to date    Is Elon Musk even allowed to send his car to deep space?    Elon Musk says Tesla is working on custom AI chips    Tesla just received its largest preorder of Semi trucks yet    Elon Musk told us he was sending a car to space  then said he totally made it up    Elon Musks giant battery is now delivering power to South Australia    Teslas Model 3 has a range of 310 miles  EPA confirms    Teslas electric Semi trucks are priced to compete at $150 000    Elon Musk has finished building the worlds biggest battery in less than 100 days    What should truckers call Teslas new Semi?    Forget the Roadster and the Semi  Teslas fate still hinges on the Model 3    Teslas portable phone-charging battery will complement your Tesla-branded life    Everything we learned from the Tesla Semi and Roadster event    Walmart says its preordered 15 of Teslas new semi trucks    Watch this supercut of Elon Musk unveiling Teslas new Semi truck and Roadster     The Tesla Roadster will start at $200 000    Teslas new Roadster will be the fastest production car ever made    All of the news from Teslas electric semi truck event    This is the Tesla Semi truck    Tesla unveils its largest Supercharger station in the US  and it kind of looks like a truck stop    Does the world need a Tesla truck?    How to watch tonights Tesla semi truck unveiling    What we know about the Tesla semi truck before the Thursday reveal    Tesla buys automated manufacturing firm as it struggles with production    Tesla misses first major Model 3 goal in worst financial quarter ever    Tesla hit with labor complaint on behalf of fired factory workers    Daimler shows off an electric truck ahead of Tesla     Tesla starts energy storage at hospital to help Puerto Rico    Tesla lays off hundreds of SolarCity employees as part of broader housecleaning    Teslas Autopilot is supposed to deliver full self-driving  so why does it feel stuck in the past?    Tesla has reached a deal to build a factory in China      Tesla hit with another lawsuit  this time alleging anti-LGBT harassment    Former Tesla factory workers allege racial harassment in new lawsuit    Tesla fires hundreds of workers even as Model 3 production ramps up    Musk delays Tesla Semi unveil to focus on Model 3  Puerto Rico    Elon Musk offers to rebuild Puerto Ricos power grid using solar     Porsches Tesla rival spotted in the wild for the first time    Image of Teslas electric semi truck surfaces    Tesla is behind on Model 3 production    Heres our closest look at the Tesla Model 3 touchscreen yet    A nine-year-old reviews the Tesla Model X     Tesla wants to turn some of its Supercharger stations into convenience stores    Tesla is getting rid of the cheapest Model S    Tesla is reportedly developing its own chip with AMD for self-driving cars    Porsches all-electric Tesla rival could cost less than $100 000    Tesla plans to unveil its all-electric semi truck on October 26th    Lack of safeguards in Teslas Autopilot contributed to fatal crash    Tesla reveals smaller Supercharger stations made for cities    Tesla extended the range of some Florida vehicles for drivers to escape Hurricane Irma    Tesla Model S P100D review: the ultimate status symbol of California cool    Teslas own Hyperloop pod sets record with 220 mph test run    Heres a Tesla inside Elon Musks LA tunnel    Teslas electric semi truck will reportedly have a range of 200-300 miles    Elon Musk rolled out Autopilot despite engineers safety concerns: report    The Tesla Model 3 reminds me of all the times the electronics failed in my first car    The Tesla Model 3 should have a heads-up display    Teslas upcoming electric semi truck will be able to drive itself    Nissan Leaf will be cheaper than Tesla Model 3 and Chevy Bolt  but have less range    Tesla has been working on a backup plan in case its self-driving promises fail    Leaked photos of new all-electric Leaf provide first look at Nissans Tesla killer    Italian Tesla drivers set distance record after driving Model S 670 miles on a single charge    Tesla drops Model X price by another $3 000    Elon Musk reportedly wants to build his own hyperloop  tunnels and all    The Tesla Model 3 revealed and iPhone leaked: this week on The Vergecast    Chevy Bolt beats the Tesla Model S in a new Consumer Reports range test    Elon Musk is one of the first customers of Teslas Solar Roof    Tesla shifts focus to bring Model Y to market faster    Tesla has moved 47 000 cars so far this year    A real hyperloop is almost here  and its not what Elon Musk envisioned    Teslas long-serving battery tech chief has stepped down: report    Teslas Model 3 isnt a luxury car  but its priced like one    How the Tesla Model 3 compares to the Model S and Chevy Bolt    Alphabet could soon be competing with Tesla in renewable energy storage    Teslas Model 3 and Apples iPhone have a few things in common    Elon Musk should stop making that stupid sex joke about Teslas car names    A closer look at Tesla Model 3s spartan interior    Tesla Model 3 event  in photos    An emotional Elon Musk thanks the people who are still waiting to get their Model 3    The Tesla Model 3 interior doesn t look like any car you ve ever seen    Everything we just learned about the Tesla Model 3    Tesla Model 3 first drive: this is the car that Elon Musk promised    How Tesla changed the auto industry forever    Watch the Tesla Model 3 party    What do Tesla Model 3 buyers want from the most important electric car ever built?    Elon Musk dismisses Mark Zuckerbergs understanding of AI threat as limited    Elon Musk says he has a green light to build a NY-Philly-Baltimore-DC hyperloop    Elon Musk now owns X.com  the defunct domain of his second startup    Two guys did a coast-to-coast Cannonball Run in a Tesla Model S for a new record    Elon Musk shows off first production Tesla Model 3    Tesla wins bid to build worlds largest lithium-ion battery for South Australia    Everything you need to know about Tesla Model 3  which is starting production    Tesla factory reportedly described as a predator zone by female employees    First production Tesla Model 3 expected Friday  Elon Musk says    Leaked photos of the Tesla Model 3 ignite an internet power struggle    Tesla confirms its in talks to build a factory in China    Tesla enthusiasts set hypermiling record after driving Model S 560 miles on a single charge    Teslas Autopilot software head leaves the company six months after joining from Apple    Tesla offers another hint that the Model 3 is on the way    ScreenDrive: Tesla Model S is the epitome of a tablet on wheels    Watch Teslas first Model X crash test  which earned it 5 stars across the board    7 things we learned from Elon Musks Tesla shareholder meeting    What to expect at Teslas annual shareholder meeting    US insurer hikes Tesla premiums due to  higher-than-average  claim rates    Elon Musk steps down from Trump advisory councils over Paris climate decision    Tesla fires female engineer who made claims of pervasive harassment    Elon Musk says he ll quit Trumps advisory councils if US leaves Paris climate deal    Injury rates at Teslas auto factory were 31 percent higher than the industry average  report finds    Teslas bumpy relationship with Consumer Reports exposes a bigger challenge    Ford is vying for Tesla magic by doubling down on its self-driving dreams    New Tesla owners can now get free charging with a referral code    Tesla opens up preorders for its solar roof    Tesla wants to make self-driving cars a reality by collecting more video data from drivers    Nows your chance to help Elon Musk name his tunneling machine    Elon Musk hints Tesla may not build a bus after all    Elon Musk just teased some tantalizing details about Tesla Model Y    Tesla shipped a record 25 051 vehicles last quarter    Tesla is opening its own body repair shops this year    Tesla executives launch a mysterious startup for materials recycling    10 things we learned about tunnels and Tesla from Elon Musks TED interview    Microsoft event  iPhone sales  Tesla Model 3 progress  and more in the week ahead    Consumer Reports lowered Teslas ratings over concerns about auto braking    Teslas German automation expert reportedly ousted after just six months    Tesla is making a big expansion to its Supercharger network    Elon Musks dreams of merging AI and brains are likely to remain just that  for at least a decade    Tesla app update lets Powerwall owners keep an eye on their electricity    Tesla withdraws lawsuit against former Autopilot head  gets $100k in settlement    Teslas cheapest Model S just got cheaper    Cadillac has a secret weapon in its quest to beat Tesla at self-driving    Tesla will unveil the finished Model 3 in July    Elon Musk says Tesla will unveil its tractor-trailer truck in September    Tesla is the most valuable US carmaker because of hope  not results    Cadillac takes aim at Teslas Autopilot with hands-free Super Cruise technology  available this fall    Tesla says the Model S  not the Model 3  is its flagship car    Tesla is now making almost as many SUVs as sedans    Tesla updates Autopilot  Autosteer now works to 80 mph in new cars    Lucid Motors sleek Tesla-killer redefines electric luxury    Elon Musk launches Neuralink  a venture to merge the human brain with AI    Elon Musk hints that the Tesla Model 3 will have more range than the Chevy Bolt    Elon Musk shares video of near-final Model 3  but says he wont drive one    Tesla is discontinuing its cheapest car  the 60kWh Model S    Tesla to raise $1 billion through stock and loan offerings    A Tesla owner made his car look like a cartoon with a clever vinyl wrap    Watch a Tesla Model 3 prototype drive down the street    Elon Musk bets he can fix Australias energy issue in 100 days or its free    Bentley challenges Teslas idea of electric luxury with a gorgeous new concept car    Tesla built a huge solar energy plant on the island of Kauai    Elon Musk made hats for his boring tunnel company    A letter from a 10-year-old inspired Tesla to launch a video contest    Tesla engineer alleges unwanted and pervasive harassment in lawsuit against electric carmaker    Elon Musk says UAW tactics are disingenuous or outright false    Tesla is doubling the number of Supercharger locations in North America    Tesla is planning at least three more Gigafactory locations    Kernel is trying to hack the human brain  but neuroscience has a long way to go    Elon Musk dishes more dirt on his tunneling plans    Elon Musk kept his harshest criticism of Trumps immigration ban in his Twitter drafts    Elon Musk thinks humans need to become cyborgs or risk irrelevance    Elon Musk accuses the UAW of paying an employee to unionize Tesla    Tesla is retooling its factory for Model 3 production    Tesla owners can now see if Superchargers are occupied    Missing Autopilot 2 features should be coming to HW2 Teslas by next month    The Tesla Model 3 wont get a 100kWh battery    Elon Musks Tesla and SpaceX join immigration amicus brief    Millions of Tesla battery cells are powering thousands of LA homes    Trump is turning Elon Musk into a crony capitalist    Could Elon Musk be considering using his Boring Company for hyperloop?    Elon Musk explains why he won t quit Donald Trumps advisory council    Florida Highway Patrol releases full investigation into fatal Tesla crash: read it here    Tesla Motors changes company name to just Tesla    Elon Musk: refugees dont deserve to be rejected    Tesla sues former Autopilot head for breach of contract and employee poaching    Elon Musk:  Without tunnels  we will all be in traffic hell forever     Elon Musk still claims hes serious about boring tunnels    Tesla says focus on safety is driving the step-by-step Autopilot 2 rollout    Tesla rolling out Autopilot to cars built since October  will limit Autosteer to 45 mph    Driver in fatal Tesla Autopilot crash had seven seconds to take action    Tesla knew drivers were going to turn on Autopilot and then stop paying attention    Teslas crash rate dropped 40 percent after Autopilot was installed  Feds say    Fatal Tesla Autopilot accident investigation ends with no recall ordered    Tesla will also make Model 3 motors at its Nevada Gigafactory    Tesla helps Sierra Nevada Brewing make  green  beer    Teslas latest Autopilot update rolls back its speed cap on undivided roads    Tesla details Supercharging fees for new buyers    Tesla will power its Gigafactory with a 70-megawatt solar farm    Teslas new Autopilot chief is a longtime Apple veteran    Riding with Lucid Motors  the 1 000-horsepower electric car built to beat Tesla    Tesla preparing Autopilot 2 test deployment  possible wide rollout by this week    Mercedes will give Teslas Autopilot its first real competition this year    Battery cells are now in production at Teslas Gigafactory    Tesla delivered over 76 000 vehicles in 2016  falling slightly short of goal    Tesla extends unlimited free supercharging incentive through mid-January    The Verge 2016 tech report card: Tesla    Tesla and Panasonic to build solar panels together following SolarCity acquisition    Elon Musk says new version of Teslas Autopilot could be coming next week    Teslas new update restricts Autopilot to the speed limit on undivided roads    UK Tesla prices to increase 5 percent following Brexit currency fluctuations    Uber launches electric fleet of Teslas in Madrid    Tesla owners who leave cars at Superchargers after charging will pay $0.40/minute')

  
  

In [0]:
def intoWordArray(article):    
    article = str(article)
    word = ''
    arrayOfWords = []
    disWorFrequencies = []

    for element in article:
        if element in ('.',' ',',','(',')'):
            if len(arrayOfWords) == 0:
                arrayOfWords.append(word)
                disWorFrequencies.append(1)
                word = ''
            for index in range(0,len(arrayOfWords)):
                if word == arrayOfWords[index]:
                    disWorFrequencies[index] += 1
                    word = ''
                    break;
                elif index == len(arrayOfWords)-1:
                    arrayOfWords.append(word)
                    disWorFrequencies.append(1)
                    word = ''
        else:
            word += element

    index = 0

    while index < len(arrayOfWords):
        for element in ['']:#,'the', 'to', 'a', 'and', 'in', 'as']:
            if element == arrayOfWords[index]:
                del arrayOfWords[index]
                del disWorFrequencies[index]
        index = index +1
    return arrayOfWords
  
intoWordArray('fuck you man ')

['fuck', 'you', 'man']

In [0]:
from google.colab import drive 
drive.mount('/content/gdrive')
import pandas as pd
import tensorflow

stockDf = pd.read_csv("gdrive/My Drive/tesla.csv")
articleDf = pd.read_csv("gdrive/My Drive/refinedvergeArticles.csv")


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
print(referenceDict)
referenceKeys = list(referenceDict.keys())

{'Tesla': 305, 'Elon': 155, 'Model': 123, 'Musk': 118, 'of': 87, 'is': 85, 'Teslas': 84, '3': 77, 'for': 53, 'will': 49, 'on': 49, 'its': 48, 'Autopilot': 43, 'says': 40, 'with': 38, 'Musks': 37, 'at': 35, 'new': 33, 'The': 23, 'cars': 23, 'car': 22, 'be': 21, 'by': 20, 'electric': 20, '000': 20, 'his': 19, 'from': 19, 'after': 18, 'first': 18, 'self-driving': 17, 'S': 17, 'truck': 17, 'about': 16, 'it': 16, 'production': 15, 'has': 14, 'now': 14, 'this': 14, 'build': 14, 'are': 13, 'Y': 13, 'over': 12, 'but': 12, 'you': 11, 'crash': 11, 'can': 11, 'company': 11, 'Supercharger': 11, 'that': 11, 'battery': 11, 'into': 11, 'reportedly': 11, 'still': 10, 'SEC': 10, 'factory': 10, 'report': 10, 'making': 10, 'was': 10, 'than': 10, 'Roadster': 10, 'we': 9, 'safety': 9, 'startup': 9, 'tunnel': 9, 'made': 9, 'X': 9, 'not': 9, 'China': 9, 'week': 9, 'Boring': 9, 'more': 9, 'he': 9, 'just': 9, 'Semi': 9, 'tweets': 8, 'solar': 8, 'an': 8, 'AI': 8, 'What': 8, 'up': 8, 'Gigafactory': 8, 'power': 8

In [0]:
def convertToTraining(articleTitle):
  trainingExample = []
  for element in range(0,len(referenceKeys)):
    trainingExample.append(0)
  articleKeys = intoWordArray(articleTitle + ' ')
  print(articleKeys)
  for element in articleKeys:
    for index in range(0,len(referenceKeys)):
      if referenceKeys[index] == element:
        trainingExample[index] += + 1
  return trainingExample
print(convertToTraining('Tesla Model the Musk '))


print(referenceKeys)

['Tesla', 'Model', 'the', 'Musk']
[1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [0]:
# To create another attribute

def findChangeQuality(row):
    change = "neutral"
    if row['articleChange'] > 1:
        change = "positive"
    elif row['articleChange'] < -1:
        change = 'negative'
    return change
articleDf['change quality'] = articleDf.apply(findChangeQuality, axis=1)
print(articleDf['change quality'])

answerDistributions = []

# Distinguishing between ordinal/numerical encoding of data for answer distributions and one hot encoding

# USE THIS FOR NUMERICAL ENCODING
positive = 0
negative = 1
neutral = 2

# USE THIS FOR ONE HOT ENCODING
# positive = [1,0,0]
# negative = [0,1,0]
# neutral = [0,0,1]


#Output space comprises of three, where the first is positive [1,0,0], the second is negative[0,1,0], and the third is neutral[0,0,1]
for element in articleDf['change quality']:
  answerDisribution = []
  if element == 'positive':
    answerDisribution = positive
  elif element == 'negative':
    answerDisribution = negative
  else:
    answerDisribution = neutral
  answerDistributions.append(answerDisribution)
  print(element+ '      '+ str(answerDisribution)) 
 


In [0]:
trainingDataInputs = []
trainingDataOutputs = []
trainingDataOutputsTWO = []
testingDataInputs = []
testingDataOutputs = []
testingDataOutputsTWO = []



testSetLength = 40
for x in range(0, len(articleDf['article'])-testSetLength):
  trainingFormInput = convertToTraining(articleDf['article'][x])
  trainingDataInputs.append(trainingFormInput)
  
  trainingFormOutput = articleDf['articleChange'][x]
  trainingDataOutputs.append(trainingFormOutput)
  
  trainingDataOutputsTWO.append(answerDistributions[x])
                                
for x in range(len(articleDf['article'])-testSetLength, len(articleDf['article'])):
  testingFormInput = convertToTraining(articleDf['article'][x])
  testingDataInputs.append(testingFormInput)
  
  testingFormOutput = articleDf['articleChange'][x]
  testingDataOutputs.append(testingFormOutput)
  
  testingDataOutputsTWO.append(answerDistributions[x])

print(len(trainingDataInputs))
print(len(trainingDataOutputs))
print(len(trainingDataOutputsTWO))

print(len(testingDataInputs))
print(len(testingDataOutputs))
print(len(testingDataOutputsTWO))


In [0]:
import tensorflow as tf
from tensorflow import keras
from keras.callbacks import LambdaCallback

import numpy as np
import matplotlib.pyplot as plt

# Rememeber set names:
#   trainingDataInputs = []
#   trainingDataOutputs = []
#   testingDataInputs = []
#   testingDataOutputs = []


print(tf.__version__)

x_train = np.array(trainingDataInputs)
print(x_train)
print(type(x_train))
x_test = np.array(testingDataInputs)

y_train = np.array(trainingDataOutputsTWO)

print(y_train)

print(type(y_train))
y_test = testingDataOutputsTWO

print(x_train[5])
print(articleDf['articleChange'][5])

model = tf.keras.models.Sequential()
#model.add(tf.keras.layers.Dense(3, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(3, activation = tf.nn.softmax))

model.compile(optimizer = 'adam',
             loss = 'sparse_categorical_crossentropy',
             metrics = ['accuracy'])



model.fit(x_train, y_train, epochs = 3)

# for x in range(model.get_weights()):
#   print(referenceKeys[x])

1.13.1
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]
<class 'numpy.ndarray'>
[0 0 1 1 1 1 1 1 1 0 1 1 1 1 2 2 2 2 2 1 0 0 0 0 0 2 0 0 2 2 1 2 2 2 1 1 1
 1 1 2 2 2 2 2 0 0 0 0 2 2 2 2 2 1 2 1 2 2 2 2 0 2 2 2 2 2 1 0 2 1 1 1 2 0
 2 0 0 2 2 1 2 1 0 2 0 0 2 0 1 2 2 1 1 1 1 1 2 2 2 0 0 0 1 0 2 2 2 2 2 2 2
 2 2 0 0 1 1 1 2 2 2 1 1 0 0 2 2 2 0 1 1 1 1 2 2 1 1 2 2 1 1 1 0 0 0 0 0 0
 0 0 0 2 1 2 2 2 0 2 1 1 1 1 1 2 2 2 2 0 2 2 2 0 2 2 1 1 0 2 1 2 2 2 0 2 0
 1 2 2 0 0 1 1 1 0 1 0 2 0 2 2 0 2 1 1 1 2 0 0 2 2 1 0 2 1 2 1 1 2 2 2 2 0
 2 0 2 2 2 1 1 1 1 0 2 1 2 0 0 1 1 0 1 1 0 2 2 2 2 1 1 2 0 2 2 2 2 2 0 2 1
 1 1 0 0 0 0 0 1 1 1 1 2 1 1 2 0 2 1 1 1 1 0 0 1 0 1 1 1 2 2 0 2 2 2 2 2 1
 2 2 2 2 1 1 1 1 1 1 2 2 2 2 2 0 2 1 2 1 1 1 2 2 1 0 2 0 0 0 0 2 1 1 1 1 2
 0 2 2 0 2 1 2 2 2 2 2 2 2 2 2 2 2 0 0 0 2 2 0 0 0 1 1 1 1 1 2 2 2 2 2 2 2
 2 2 2 1 2 0 2 2 2 2 1 1 2 0 2 1 1 1 0 0 0 0 1 1 2 0 0 2 2 0 1 0 1 1 1 1 1
 0 0 2 2 2 0 1 0 2 2 0 0

In [0]:
for x in range(1,len(referenceKeys)):
  print(referenceKeys[x])
  print(model.get_weights()[0][x])

Elon
[ 0.03896656 -0.06888554 -0.02808861]
Model
[-0.03089053 -0.04216719 -0.01898305]
Musk
[0.01974951 0.01886275 0.00010065]
of
[-0.00801006  0.04845344  0.06280287]
is
[-0.09346396  0.05083118  0.01335368]
Teslas
[0.00827596 0.02744463 0.07765801]
3
[0.03478811 0.06878351 0.04692444]
for
[ 0.03536675 -0.04202783  0.04406557]
will
[-0.0266432  -0.04163656  0.06870426]
on
[-0.04034224 -0.06200222  0.08466694]
its
[-0.04014117 -0.06053004 -0.0140522 ]
Autopilot
[-0.00923795  0.03998813 -0.03401871]
says
[0.00940293 0.00608876 0.07241346]
with
[-0.06618945  0.02979907  0.08171161]
Musks
[-0.05435191  0.05710332  0.06676193]
at
[0.02423806 0.03729486 0.06352088]
new
[-0.01892095  0.04626619 -0.02066674]
The
[-0.07870876 -0.04731228 -0.04554892]
cars
[ 0.0220746   0.00881418 -0.03868219]
car
[-0.058154   -0.06739201  0.02451064]
be
[0.03952395 0.07076594 0.07473411]
by
[-0.03722009  0.06328838  0.03203256]
electric
[-0.0291223   0.0546574  -0.03867295]
000
[ 0.05865417 -0.0192774   0.0753